@startuml
title CityGML 東京都大田区南六郷三丁目

map "13111-bldg-466 :建築物" as bldg466 {
 bldg:Building:id => BLD_e61455af-37cd-4d75-ba2b-ab419880b805
 bldg:Building:stringAttribute[name="建物ID"] => 13111-bldg-466
 bldg:Building:stringAttribute[name="13_区市町村コード_大字・町コード_町・丁目コード"] => 13111058003
 bldg:lod0RoofEdge:Polygon:posList:height => 6.84
 bldg:usage => 411 (住宅)
 bldg:yearOfConstruction => 1976
 bldg:measuredHeight => 4.6 m
 bldg:storeysAboveGround => 2
 bldg:storeysBelowGround => 1
 bldg:lod0RoofEdge => 屋根形状
 bldg:lod1Solid => 2.671 (最低標高)
 LocalityName[type="Town"] => 東京都大田区南六郷三丁目
 Envelope:srsName => http://www.opengis.net/def/crs/EPSG/0/6697
}

map "13111-bldg-365 :建築物" as bldg365 {
 bldg:Building:id => BLD_e61455af-37cd-4d75-ba2b-ab419880b805
 bldg:Building:stringAttribute[name="建物ID"] => 13111-bldg-365
 bldg:Building:stringAttribute[name="13_区市町村コード_大字・町コード_町・丁目コード"] => 13111058003
 bldg:lod0RoofEdge:Polygon:posList:height => 5.127
 bldg:measuredHeight => 2.4 m
 bldg:lod0RoofEdge => 屋根形状
 bldg:lod1Solid => 2.749 (最低標高)
 LocalityName[type="Town"] => 東京都大田区南六郷三丁目
 Envelope:srsName => http://www.opengis.net/def/crs/EPSG/0/6697
}

bldg365 -[hidden]- bldg466
@enduml
