@startuml

map "building :Relation" as building {
 type => building
 building => yes
 name => 大田病院
 height => 17.199
 addr:ref => 13111007004
 addr:full => 東京都大田区大森東四丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697
}

map "part A :Area" as partA {
 building:part => yes
 name => 大田病院
 height => 17.199
 addr:ref => 13111007004
 addr:full => 東京都大田区大森東四丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n 13111-bldg-56522
}

map "B :Area" as partB {
 building:part => yes
 height => 5.5360000000000005
 addr:ref => 13111007004
 addr:full => 東京都大田区大森東四丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n 13111-bldg-55333
}

building o-- partA : member\n[role=part]
building o-- partB : member\n[role=part]
@enduml