@startuml
map "building : Relation" as building {
 type => building
 building => yes
 building:levels => 3
 building:levels:underground => 1
 name => 大田病院
 height => 17.199
 addr:ref => 13111007004
 addr:full => 東京都大田区大森東四丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697
}

map "multipolygon :Relation" as multipolygon {
 type => multipolygon
 building => yes
 building:levels => 3
 building:levels:underground => 1
 name => 大田病院
 height => 17.199
 addr:ref => 13111007004
 addr:full => 東京都大田区大森東四丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697
}

map "outline :Way" as outer {
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697
}

map "e- :Way" as e {
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697
}

map "13111-bldg-56522 :Area" as A {
 building:part => yes
 building:levels => 2
 building:levels:underground => 1
 name => 大田病院
 height => 17.199
 addr:ref => 13111007004
 addr:full => 東京都大田区大森東四丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n 13111-bldg-56522
}
map "13111-bldg-55333 :Area" as B {
 building:part => yes
 building:levels => 3
 height => 5.5360000000000005
 addr:ref => 13111007004
 addr:full => 東京都大田区大森東四丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n 13111-bldg-55333
}

building o-- multipolygon : member\n[role=outline]
building o-- A : member\n[role=part]
building o-- B : member\n[role=part]

multipolygon  o-- outer : member\n[role=outer]
multipolygon  o-- e : member\n[role=inner]
@enduml
