@startmindmap
title CityGML 構造

* core:CityModel
** gml:boundedBy
*** gml:Envelope
**** srsName
*****_ "http://www.opengis.net/def/crs/EPSG/0/6697"
**** gml:lowerCorner
*****_ "35.56633413507695 139.73733775689777 0.121"
**** gml:upperCorner
*****_ "35.57505092590962 139.75013607178525 31.288"

** core:cityObjectMember
*** bldg:Building
**** gml:id
*****_ "BLD_4ebf61e7-bbc4-493c-aa9c-5afc8f7b975d"
**** gml:name
*****_ "大田病院"
**** gen:stringAttribute name="13_区市町村コード_大字・町コード_町・丁目コード"
*****_ "13111007004"
**** gen:stringAttribute name="建物ID"
*****_ "13111-bldg-56522"

**** bldg:class codeSpase="Building_class.xml"
*****_ "3001"

**** bldg:usage codeSpace="Building_usage.xml"
*****_ "402"

**** bldg:measuredHeight
*****_ "13.3"

**** bldg:lod0RoofEdge
***** gml:Polygon
****** gml:exterior
******* gml:LinearRing
******** gml:posList
*********_ [{緯度 経度 高度}...]
****** gml:interior
******* gml:LinearRing
******** gml:posList
*********_ [{緯度 経度 高度}...]

**** bldg:lod0FootPrint
***** gml:Polygon
****** gml:exterior
******* gml:LinearRing
******** gml:posList
*********_ [{緯度 経度 高度}...]
****** gml:interior
******* gml:LinearRing
******** gml:posList
*********_ [{緯度 経度 高度}...]

**** bldg:lod1Solid
***** gml:exterior
****** gml:Polygon
******* gml:exterior
******** gml:LinearRing
********* gml:posList
**********_ [{緯度 経度 高度}...]

**** xAL:LocalityName Type="Town"
*****_ "東京都大田区大森西三丁目"

@endmindmap
