@startuml
package CityGML {
  class "CityGML file" as Xml {
  }
  
  class "core:CityModel" as CityModel {
    gml:boundedBy
  }

  class "core:cityObjectMember" as cityObjectMember {
  }

  class "bldg:Building" as ElemntBuilding {
    gml:id
    roofEdges : List<ElementRoofEdge>
  }

  class "bldg:lod0RoofEdge<? list of ElementWay>" as ElementRoofEdge {
  }
  
  class "gml:LinearRing" as LinearRing {
  }
  
  class "gml:posList" as posList {
  }

  Xml o-- CityModel
  CityModel "*" o-- "1" cityObjectMember
  cityObjectMember "*" o-- "1" ElemntBuilding
  ElemntBuilding "*" o-- "1" ElementRoofEdge
  ElementRoofEdge o-- LinearRing
  LinearRing o-- posList
}

package "osm.surveyor.osm" as osm {
  class ElementRelation {
    id : long
    action : String
    visible : bool
    members : List<ElementMember>
    tags : List<ElementTag>
    addTag(k, v)
    addMember(way:ElemntWay, role:String)
    printout(:OsmFile)
  }
  
  class ElementMember {
    ref : long
    type : String
    role : String
    way : ElementWay
    setWay(:ElementWay)
    setRole(:String)
    printout(:OsmFile)
  }

  class ElementWay {
    id : long
    action : String
    visible : bool
    nodes : List<ElementNode>
    tags : List<ElementTag>
    addTag(k, v)
    addNode(:ElementNode)
    printout(:OsmFile)
  }
  
  class ElementTag {
    k : String
    v : String
    printout(:OsmFile)
  }
  
  ElementRelation "*" o-- "0..1" ElementMember
  ElementRelation "*" o-- "0..1" ElementTag
  ElementMember "1" -- "0..1" ElementWay
  ElementWay "*" o-- "0..1" ElementTag
}

ElementRelation <|-- cityObjectMember : {type='building'}
ElementWay <|.. LinearRing : AREA
@enduml
