@startuml
title Database tables

interface osmObject {
 +id : integer
 action : string=[null,"modify"]
 timestamp : string
 uid : string
 username : string
 visible : boolean
 version : string
 changeset : string
 orignal : boolean = false
}

class Relation {
}

class Member {
 +relationid : integer
 ref : integer
 type : String = "way"
 role : String
}

class Way {
 geom : GEOMETRY(POLYGON, 4326)
}

class Nd {
 wayid : integer
 ref : integer
}

class Node {
}

class Tag {
 +id : integer
 key : string
 value : string　
}

osmObject <|-- Relation
osmObject <|-- Way
osmObject <|-- Node
osmObject "*" - "1" Tag : [osmObject.id=Tag.id]

Relation "*" - "*" Way
(Relation, Way) .. Member : [Relation.id=Member.relationid]\n[Way.id=Member.ref] 

Way "2..*" - "1..2" Node
(Way, Node) .. Nd : [Way.id=Nd.wayid]\n[Node.id=Nd.ref]

@enduml