@startuml
title CityGML-OSM 第一段階の実行環境イメージ

cloud Internet {
 node "3D都市モデル\nポータルサイト" as zipsite
 node "変換プログラム\nダウンロードサイト" as jarsite
}

() "1.download" as jardownload
jarsite .. jardownload

() "2.download" as zipdownload
zipsite .. zipdownload

file ".zip" as zip
() "3. unzip" as unzip
zip .. unzip

node PC {

 folder 任意のフォルダ {
  file "citygml-get-0.0.4-jar-with-dependencies.jar" as jar
  collections "*_op2.gml" as gml
 
  unzip --> gml
  () "4.cmd" as cmd
 
  collections "*_op2.osm\n第一段階生成物" as osm
 }

 node JOSM
 () "5.drop" as drop

}

jardownload --> jar
zipdownload --> zip

jar .. cmd
gml .. cmd
cmd -> osm
osm .. drop
drop -> JOSM
@enduml
