@startuml
title CityGML-OSM 第二段階の実行環境イメージ

cloud Internet {
 node "OpenStreetMap\nAPI v0.6" as osmapi
}

() "3.第一段階" as cmd3

node PC {
 folder 任意のフォルダ {
  file "citygml-osm-1.3.x-jar-with-dependencies.jar" as jar
  collections "`*.osm`\n第一段階 生成物" as osm
  cmd3 -> osm
 
  () "4.cmd" as cmd
  jar .. cmd
  osm .. cmd
  osmapi .. cmd
 
  collections "*_op2.mrg.osm\n第二段階 生成物" as mrg
  cmd -> mrg
 }

 () "5.drop" as drop
 node JOSM
}

mrg .. drop
drop -> JOSM
@enduml