@startuml
title CityGML-OSM 第三段階の実行環境イメージ

 () "第一段階" as step1

 () "第二段階" as step2

node PC {

 folder 任意のフォルダ {
  file "citygml-osm-jar-with-dependencies.jar" as jar
  collections "`*.osm`\n第一段階 生成物" as osm
  collections "`*.org.osm`\n第二段階 生成物" as org
  step1 --> osm
  step2 --> org
 
  () "cmd 3rd" as cmd
  jar .. cmd
  osm .. cmd
  org .. cmd
 
  collections "`*.mrg.osm`\n第三段階 生成物" as mrg
  cmd -> mrg
 }

 () "drop" as drop
 node JOSM
}

mrg .. drop
drop -> JOSM
@enduml