@startuml
object "-59 : Way" as Way_59 {
  id = -59
  building = yes
  building:levels = 2
  building:levels:underground = 1
  height = 34.7
  ele = 2.7
  survey:date = 2016
  start_date = 1976
  ref:MLIT_PLATEAU = 13111-bldg-72601
  nd = [7,53,54,55,56,8]
}
note right : A

object "-60 : Way" as Way_60 {
  id = -60
  ref:MLIT_PLATEAU = 13111-bldg-72601
  nd = [7,53,54,55,56,8]
}
note bottom : A outer

object "-61 : Way" as Way_61 {
  id = -61
  ref:MLIT_PLATEAU = 13111-bldg-72601
  nd = [62,63,64,65]
}
note bottom : a1 inner

object "-10 : Way" as Way_10 {
  id = -10
  building => yes
  building:levels => 3
  height = 30.2
  ele = 3.1
  survey:date = 2016
  start_date => 1977
  ref:MLIT_PLATEAU = 13111-bldg-71799
  nd = [5,6,7,8]
}
note right : B

object "-11 : Way" as Way_11 {
  id = -11
  ref:MLIT_PLATEAU = 13111-bldg-71799
  nd = [5,6,7,8]
}

object "-67 : Way" as Way_67 {
  id = -67
  ref:MLIT_PLATEAU = 13111-bldg-72601
  nd = [68,69,70,71]
}
note bottom : a2 inner

Way_10 .[#orange] Way_11 : same position
Way_59 .[#orange] Way_60 : same position

package Part1 {
  map "-50 : Relation" as Relation_50 {
    id => -50
    type => multipolygon
    **building** => yes
    building:part => yes
    building:levels => 2
    building:levels:underground => 1
    ele => 2.7
    height => 34.7
    start_date => 1976
    survey:date => 2016
    member => [-60,-61,-67]
  }
  Relation_50::member --> Way_60 : role=outer
  Relation_50::member --> Way_61 : role=inner
  Relation_50::member --> Way_67 : role=inner

  map "-48 : Relation" as Relation_48 {
    id => -48
    type => building
    building => yes
    building:levels => 2
    building:levels:underground => 1
    ele => 2.7
    height => 34.7
    start_date => 1976
    survey:date => 2016
    member => [-59,-50]
  }
  Relation_48::member --> Way_59 : role=outline
  Relation_48::member --> Relation_50 : role=part
}

package Main {
  map "-3 : Relation" as Relation_3 {
    id => -3
    type => multipolygon
    **building** => yes
    building:part => yes
    building:levels => 3
    building:levels:underground => 1
    ele => 3.1
    height => 30.2
    start_date => 1977
    survey:date => 2016
    member => [-11]
  }
  Relation_3::member --> Way_11	: role=outer

  map "-1 : Relation" as Relation_1 {
    id => -1
    type => **building**
    building => yes
    building:levels => 3
    ele => 3.1
    height => 30.2
    start_date => 1977
    survey:date => 2016
    member => [-10,-3]
  }
  Relation_1::member --> Relation_3	: role=part
  Relation_1::member --> Way_10	: role=outline
}
@enduml
