@startuml
object "-199 : Way" as Way_199 {
  survey:date = 2016
  building = yes
  height = 34.7
  ele = 2.7
  building:levels = 3
  building:levels:underground = 1
  nd = [7,53,54,55,56,8,5,6]
}
note bottom : (A+B) outline

object "-60 : Way" as Way_60 {
  ref:MLIT_PLATEAU = 13111-bldg-72601
  nd = [7,53,54,55,56,8]
}
note bottom : A outer

object "-61 : Way" as Way_61 {
  ref:MLIT_PLATEAU = 13111-bldg-72601
  nd = [62,63,64,65]
}
note bottom : a1 inner

object "-10 : Way" as Way_10 {
  height = 30.2
  ele = 3.1
  survey:date = 2016
  start_date => 1977
  building:levels => 3
  ref:MLIT_PLATEAU = 13111-bldg-71799
  building:part => yes
  nd = [5,6,7,8]
}
note right : B

object "-67 : Way" as Way_67 {
  ref:MLIT_PLATEAU = 13111-bldg-72601
  nd = [68,69,70,71]
}
note bottom : a2 inner

package Main {
  map "-50 : Relation" as Relation_50 {
    type => multipolygon
    ref:MLIT_PLATEAU => 13111-bldg-72601
    start_date => 1976
    survey:date => 2016
    building:levels => 2
    building:levels:underground => 1
    height => 34.7
    ele => 2.7
    building:part => yes
    member => [-60,-61,-67]
  }
  note right : A
  Relation_50::member --> Way_60 : role=outer
  Relation_50::member --> Way_61 : role=inner
  Relation_50::member --> Way_67 : role=inner

  map "-1 : Relation" as Relation_1 {
    type => building
    survey:date => 2016
    building => yes
    height => 34.7
    ele => 2.7
    building:levels => 3
    building:levels:underground => 1
    member => [-10,-50,-199]
  }
  note right : (A+B)
  Relation_1::member --> Way_199	: role=outline
  Relation_1::member --> Relation_50	: role=part
  Relation_1::member --> Way_10	: role=part
}
@enduml

