@startuml
map "building :Relation" as buildingA {
 type => building
 building => yes
 height => 5.4025
 addr:ref => 13111058003
 addr:full => 東京都大田区南六郷三丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n 13111-bldg-365
}

map "multipolygon A :Relation" as polygonA {
 type => multipolygon
 building => yes
 height => 5.4025
 addr:ref => 13111058003
 addr:full => 東京都大田区南六郷三丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n 13111-bldg-365
}

map "part A :Area" as partA {
 building:part => yes
 height => 5.4025
 addr:ref => 13111058003
 addr:full => 東京都大田区南六郷三丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n 13111-bldg-365
}

map "outer A :Area" as outerA {
 height => 5.4025
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n 13111-bldg-365
}

buildingA o-- partA : member\n[role=part]
buildingA o-- polygonA : member\n[role=outline]
polygonA o-- outerA : member\n[role=outer]
partA -[hidden]- outerA


map "building B :Relation" as buildingB {
 type => building
 building => yes
 height => 6.84
 addr:ref => 13111058003
 addr:full => 東京都大田区南六郷三丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n 13111-bldg-466
}

map "multipolygon B :Relation" as polygonB {
 type => multipolygon
 building => yes
 height => 6.84
 addr:ref => 13111058003
 addr:full => 東京都大田区南六郷三丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n 13111-bldg-466
}

map "B :Area" as partB {
 building:part => yes
 height => 6.84
 addr:ref => 13111058003
 addr:full => 東京都大田区南六郷三丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n 13111-bldg-466
}

map "outer B :Area" as outerB {
 height => 6.84
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n 13111-bldg-466
}

buildingB o-- partB : member\n[role=part]
buildingB o-- polygonB : member\n[role=outline]
polygonB o-- outerB : member\n[role=outer]
partB -[hidden]- outerB
@enduml