@startuml
map "building : Relation" as building {
 type => building
 building => yes
 height => 32.852000000000004
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697
}

map "multipolygon :Relation" as multipolygon {
 type => multipolygon
 building => yes
 height => 32.852000000000004
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697
}

map "outline :Area" as outer {
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697
}

map "a1- :Area" as a1 {
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n BLD_4ba3c7be-18a0-461a-9305-464fa2cfc57f
}
map "a2- :Area" as a2 {
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n BLD_4ba3c7be-18a0-461a-9305-464fa2cfc57f
}

map "A :Area" as A {
 building:part => yes
 height => 32.852000000000004
 addr:ref => 13111006003
 addr:full => 東京都大田区大森西三丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n BLD_4ba3c7be-18a0-461a-9305-464fa2cfc57f
}
map "B :Area" as B {
 building:part => yes
 height => 6.038
 addr:ref => 13111006003
 addr:full => 東京都大田区大森西三丁目
 source => MLIT_PLATEAU;\n http://www.opengis.net/def/crs/EPSG/0/6697\n BLD_4ebf61e7-bbc4-493c-aa9c-5afc8f7b975d
}

building o-- multipolygon : member\n[role=outline]
building o-- A : member\n[role=part]
building o-- B : member\n[role=part]

multipolygon  o-- outer : member\n[role=outer]
multipolygon  o-- a1 : member\n[role=inner]
multipolygon  o-- a2 : member\n[role=inner]
@enduml
