@startuml
object "-36 : Way" as Way_36 {
  height = 4.2
  ele = 0
  survey:date = 2017
  building => yes
  ref:MLIT_PLATEAU = 27100-bldg-80114
  nd = [27,28,29,30,31,32,33,34]
}
object "-37 : Way" as Way_37 {
  ref:MLIT_PLATEAU = bldg_af5a6580-XXXX
  nd = [27,28,29,30,31,32,33,34]
}
Way_36 .[#orange]. Way_37 : same position

object "-10 : Way" as Way_10 {
  height = 3.02
  ele = 0
  survey:date = 2017
  building:part => yes
  ref:MLIT_PLATEAU = 27100-bldg-80286
  nd = [5,6,7,8]
}

object "-21 : Way" as Way_21 {
  height = 0
  ele = 0
  survey:date = 2017
  ref:MLIT_PLATEAU = 27100-bldg-80281
  building:part => yes
  nd = [16,17,18,19]
}

package Part1 {
  map "-1 : Building" as Relation_1 {
    type => building
    ele => 0
    survey:date => 2017
    height => 0
    building => yes
  }
}
package Main {
  map "-25 : Multipolygon" as Relation_25 {
    type => multipolygon
    ref:MLIT_PLATEAU => bldg_af5a6580-XXXX
    survey:date => 2017
    height => 4.2
    ele => 0
    building:part => yes
    member => [-37,-38,-44]
  }
  Relation_25::member --> Way_37 : role=outer
  
  map "-23 : Building" as Relation_23 {
    height => 4.2
    type => building
    ele => 0
    survey:date => 2017
    building => yes
    member => [-36,-25,-10,21]
  }
  Relation_23::member --> Way_36 : role=outline
  Relation_23::member --> Relation_25 : role=part
  Relation_23::member --> Way_10 : role=part
  Relation_23::member --> Way_21 : role=part
}
package Part2 {
  map "-12 : Building" as Relation_12 {
    type => building
    ele => 0
    survey:date => 2017
    height => 0
    building => yes
  }
}
@enduml
