@startuml
object "-36 : Way" as Way_36 {
  height = 4.2
  ele = 0
  survey:date = 2017
  building => yes
  ref:MLIT_PLATEAU = 27100-bldg-80114
  nd = [27,28,29,30,31,32,33,34]
}
object "-37 : Way" as Way_37 {
  ref:MLIT_PLATEAU => bldg_af5a6580_XXXX
  nd = [27,28,29,30,31,32,33,34]
}
Way_36 .[#orange] Way_37 : same position

object "-38 : Way" as Way_38 {
  ref:MLIT_PLATEAU => bldg_af5a6580_XXXX
  nd = [5,8,7,6]
}
object "-10 : Way" as Way_10 {
  height = 0
  ele = 0
  survey:date = 2017
  building => yes
  ref:MLIT_PLATEAU = 27100-bldg-80286
  nd = [5,6,7,8]
}
object "-21 : Way" as Way_21 {
  height = 0
  ele = 0
  survey:date = 2017
  building => yes
  ref:MLIT_PLATEAU = 27100-bldg-80281
  nd = [16,17,18,19]
}
object "-11 : Way" as Way_11 {
  ref:MLIT_PLATEAU => bldg_a0e57a54_XXXX
  nd = [5,6,7,8]
}
Way_10 .[#orange]. Way_38 : same position
Way_10 .[#orange] Way_11 : same position

object "-22 : Way" as Way_22 {
  ref:MLIT_PLATEAU => bldg_65e93d25_XXXX
  nd = [16,17,18,19]
}
object "-44 : Way" as Way_44 {
  ref:MLIT_PLATEAU => bldg_af5a6580_XXXX
  nd = [16,19,18,17]
}
Way_21 .[#orange]. Way_44 : same position
Way_21 .[#orange] Way_22 : same position

package Part1 {
  map "[-3] : Multipolygon" as Relation_3 {
    type => multipolygon
    ref:MLIT_PLATEAU => bldg_a0e57a54_XXXX
    survey:date => 2017
    height => 0
    ele => 0
    building:part => yes
    member => [-11]
  }
  Relation_3::member --> Way_11 : role=outer
  
  map "[-1] : Building" as Relation_1 {
    type => building
    ele => 0
    survey:date => 2017
    **height** => **0**
    building => yes
    member => [-3,-10]
  }
  Relation_1::member --> Relation_3 : role=part
  Relation_1::member --> Way_10 : role=outline
}
package Main {
  map "[-25] : Multipolygon" as Relation_25 {
    type => multipolygon
    ref:MLIT_PLATEAU => bldg_af5a6580_XXXX
    survey:date => 2017
    height => 4.2
    ele => 0
    building:part => yes
    member => [-37,-38,-44]
  }
  Relation_25::member --> Way_37 : role=outer
  Relation_25::member --> Way_38 : role=inner
  Relation_25::member --> Way_44 : role=inner
  
  map "-23 : Building" as Relation_23 {
    height => 4.2
    type => building
    ele => 0
    survey:date => 2017
    building => yes
    member => [-25,-36]
  }
  Relation_23::member --> Relation_25 : role=part
  Relation_23::member --> Way_36 : role=outline
}
package Part2 {
  map "[-14] : Multipolygon" as Relation_14 {
    type => multipolygon
    ref:MLIT_PLATEAU => bldg_65e93d25_XXXX
    survey:date => 2017
    height => 0
    ele => 0
    building:part => yes
    member => [-22]
  }
  Relation_14::member --> Way_22 : role=outer
  
  map "-12 : Building" as Relation_12 {
    type => building
    ele => 0
    survey:date => 2017
    height => 0
    building => yes
    member => [-14,-21]
  }
  Relation_12::member --> Relation_14 : role=part
  Relation_12::member --> Way_21 : role=outline
}
@enduml
