@startuml
object "-61 : Way" as Way_61 {
  height = 4.2
  ele = 7.6
  survey:date = 2017
  building = yes
  ref:MLIT_PLATEAU => 27100-bldg-80114
  nd = [52,53,54,55,56,57,58,59]
}
object "-62 : Way" as Way_62 {
  ref:MLIT_PLATEAU => bldg_af5a6580-XXXX
  nd = [52,53,54,55,56,57,58,59]
}
Way_61 .[#orange] Way_62 : same position

object "-63 : Way" as Way_63 {
  ref:MLIT_PLATEAU => bldg_af5a6580-XXXX
  nd = [64,65,66,67]
}
object "-10 : Way" as Way_10 {
  height = 2.99
  ele = 7.6
  survey:date = 2017
  ref:MLIT_PLATEAU = 27100-bldg-80281
  building:part => yes
  nd = [5,6,7,8]
}

package Main {
  map "-50 : Multipolygon" as Relation_50 {
    type => multipolygon
    ref:MLIT_PLATEAU => bldg_af5a6580-XXXX
    survey:date => 2017
    height => 4.2
    ele => 7.6
    building:part => yes
    member => [-62,-63]
  }
  Relation_50::member --> Way_62 : role=outer
  Relation_50::member --> Way_63 : role=inner

  map "-48 : Building" as Relation_48 {
    type => building
    survey:date => 2017
    building => yes
    height => 4.2
    ele => 7.6
    member => [-61,-50,-10]
  }
  Relation_48::member --> Way_61 : role=outline
  Relation_48::member --> Relation_50 : role=part
  Relation_48::member --> Way_10 : role=part
}
@enduml
