@startuml
title e. 空白部分がある連接ビルディング / 最終型\nValidation OK

object "-584 : Way" as Way_584 {
  nd = [5,6,144..148,16]
}
note bottom : (a+b) inner

object "-18 : Way" as Way_18 {
  height = 3.7
  ele = 1.9
  survey:date = 2016
  start_date = 1977
  building:part = yes
  building:levels = 3
  ref:MLIT_PLATEAU = 13111-bldg-55333
  nd = [5 .. 16]
}
note bottom : A

object "-583 : Way" as Way_583 {
  nd = [7..11, 155..173, 124..141]
}
note bottom : (a+b) outer

object "-175 : Way" as Way_175 {
    start_date => 1976
    height => 21.6
    building:levels => 2
    building:levels:underground => 1
    name => "大田病院"
    ele => 1.6
    survey:date => 2016
    building:part => yes
  ref:MLIT_PLATEAU = 13111-bldg-56522
  nd = [124..141,7,6,144..148,16..11,155..173]
}
note bottom : B

Way_175 .[#blue] Way_18 : share nd[6,7,11..16]

package "Building (A+B)" {
  map "-585 : Relation" as Relation_585 {
    type => multipolygon
    start_date => 1976
    height => 21.6
    building:levels => 3
    building:levels:underground => 1
    name => "大田病院"
    ele => 1.6
    building => yes
    member => [-583,-584]
  }
  Relation_585::member --> Way_583 : role=outer
  Relation_585::member --> Way_584 : role=inner

  map "-120 : Relation" as Relation_120 {
    type => building
    building => yes
    name => "大田病院"
    height => 21.6
    building:levels => 3
    building:levels:underground => 1
    ele => 1.6
    member => [-175,-18,-585]
  }
  Relation_120::member --> Way_175 : role=part
  Relation_120::member --> Way_18 : role=part
  Relation_120::member --> Relation_585 : role=outline
}
@enduml
