@startuml
cloud Internet {
 node "OpenStreetMap\nAPI v0.6" as osmapi
}

 () "第一段階" as step1

node PC {

 folder 任意のフォルダ {

  file "citygml-osm-jar-with-dependencies.jar" as jar
  collections "`*.osm`\n第一段階 生成物\n(範囲のみ)" as osm
  step1 --> osm
 
  () "cmd 2nd" as cmd
  jar .. cmd
  osm .. cmd
  osmapi .. cmd
 
  file "第二段階 生成物\n既存データ\n`*.org.osm`" as org
  cmd -> org
 }

}
@enduml